# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [3]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [4]:
A = np.arange(1, 16).reshape(3,5)
print("Matrix A:")
print(A)
print("Dimension (ndim):", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Data type (dtype):", A.dtype)


Matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Dimension (ndim): 2
Shape: (3, 5)
Size: 15
Data type (dtype): int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [5]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print("Matrix B:")
print(B)
print("\nMatrix C:")
print(C)

# 1. Elementwise subtraction
subtraction = B - C
print("\n1. Elementwise Subtraction (B - C):")
print(subtraction)

# 2. Elementwise multiplication
elementwise_multiplication = B * C
print("\n2. Elementwise Multiplication (B * C):")
print(elementwise_multiplication)

# 3. Matrix multiplication
matrix_multiplication = B @ C
print("\n3. Matrix Multiplication (B @ C):")
print(matrix_multiplication)

Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix C:
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

1. Elementwise Subtraction (B - C):
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

2. Elementwise Multiplication (B * C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

3. Matrix Multiplication (B @ C):
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [6]:
B = np.arange(1, 10).reshape(3, 3)
print("Matrix B:\n", B)

# Exponentiate each number elementwise
exp_B = np.exp(B)
print("\nExponentiated Matrix:\n", exp_B)

# Minimum value in the whole matrix
min_value = np.min(B)
print("\nMinimum value in the whole matrix:", min_value)

# Minimum value in each row
min_value_row = np.min(B, axis=1)
print("\nMinimum value in each row:", min_value_row)

# Minimum value in each column
min_value_col = np.min(B, axis=0)
print("\nMinimum value in each column:", min_value_col)

# Index of the minimum value in the whole matrix
min_index = np.argmin(B)
print("\nIndex of the minimum value in the whole matrix:", min_index)

# Index of the minimum value in each row
min_index_row = np.argmin(B, axis=1)
print("\nIndex of the minimum value in each row:", min_index_row)

# Sum of all elements
sum_all = np.sum(B)
print("\nSum of all elements:", sum_all)

# Mean for each column
mean_col = np.mean(B, axis=0)
print("\nMean for each column:", mean_col)

# Median for each column
median_col = np.median(B, axis=0)
print("\nMedian for each column:", median_col)

Matrix B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Exponentiated Matrix:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in the whole matrix: 1

Minimum value in each row: [1 4 7]

Minimum value in each column: [1 2 3]

Index of the minimum value in the whole matrix: 0

Index of the minimum value in each row: [0 0 0]

Sum of all elements: 45

Mean for each column: [4. 5. 6.]

Median for each column: [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [7]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [8]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
When you provide fewer indices than the total number of axes, NumPy returns a sub-array corresponding to the indexed dimension.
For example, in a 2D array, A[1] selects the entire second row, while in a 3D array, A[1] would return a 2D slice.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [14]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [12]:
# Iterating elementwise
print("\nElementwise iteration:")
for element in np.nditer(A):
    print(element, end=" ")


Elementwise iteration:
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [11]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
1. Creating the a array. This creates a 1D NumPy array with numbers from 0 to 29 (shape: (30,)) - [ 0  1  2  3 ... 27 28 29]

In [ ]:
2. Reshaping a into b. This reshapes a into a 3D array (b). The shape of b is determined by reshape(2, 3, -1), meaning:
    2 blocks (or slices) along the first axis
    3 rows per block
    -1 lets NumPy automatically calculate the remaining dimension, which turns out to be 5 columns per row (because 2 × 3 × 5 = 30).

In [ ]:
3. Printing the arrays a and b

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [10]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)
print(m1.shape)
print(m2.shape)


[[2 3]
 [4 5]]
(2, 2)
(2,)


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [15]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [18]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)
print()
print(A+b)

[[1 2]
 [3 4]]
[2 2]

[[3 4]
 [5 6]]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [21]:
import numpy as np

def add_mult_matrices(matrix1, matrix2, operation):
    # Validate that inputs are of type numpy.ndarray
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise TypeError("Both inputs must be of type numpy.ndarray")

    # Validate that operation is either 'add' or 'multiply'
    if operation not in ['add', 'multiply']:
        raise ValueError("The third argument must be either 'add' or 'multiply'")

    if operation == 'add':
        # Validate that matrices have the same shape
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrices must have the same shape for addition")
        return matrix1 + matrix2
    
    elif operation == 'multiply':
        # Validate that matrix multiplication conforms to rules (columns in first = rows in second)
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Number of columns in the first matrix must equal number of rows in the second matrix for multiplication")
        return np.dot(matrix1, matrix2)

# Example usage:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Addition:\n", add_mult_matrices(A, B, 'add'))
print()
print("Multiplication:\n", add_mult_matrices(A, B, 'multiply'))

Addition:
 [[ 6  8]
 [10 12]]

Multiplication:
 [[19 22]
 [43 50]]


In [40]:
# 10.1. Vector 𝑥 = (4, 3)
x = np.array([4,3])
#(a) The dimension of 𝑥 is 2, because it contains two elements.
print(f'a) Dimension: 1 x {x.shape[0]}')
#(b) 5𝑥 = (5⋅4, 5⋅3) = (20, 15) 
print(f'b) 5x = {5*x}')
#(c) 3𝑥 = (3⋅4, 3⋅3) = (12, 9)
print(f'c) 3x = {3*x}')
#(d) 5𝑥 + 3𝑥 = (20, 15)+(12, 9) = (32, 24)
print(f"d) 5x + 3x = {add_mult_matrices(5*x, 3*x, 'add')}")
#(e) 8𝑥 = (8⋅4, 8⋅3) = (32, 24)
print(f'e) 8x = {8 * x}')
#(f) 4𝑥 − 𝑥 = (4⋅4, 4⋅3) − (4, 3) = (16, 12) − (4, 3) = (12, 9)
print(f"f) 4x - x = {add_mult_matrices(4*x, - x, 'add' )}")
#(g) Transposing 𝑥, 𝑥⊤, changes its dimension from (2,) to (2,1) if its a column vector or (1,2) if its a row vector
y = x.reshape((2,1))
print(f'g) x^T =\n{y}')
print(f'g) New dimension: {y.shape[0]} x {y.shape[1]}')
#(h) No, because 𝑥 is a row vector and 𝑥⊤ is a column vector, meaning their dimensions dont match for addition.
print(f'h) -')
#(i) 𝑥12 + 𝑥22 = 42 + 32 = 16 + 9 = 25 = 5
print(f'i) ||x|| = {np.sqrt(np.sum(x**2))}')


a) Dimension: 1 x 2
b) 5x = [20 15]
c) 3x = [12  9]
d) 5x + 3x = [32 24]
e) 8x = [32 24]
f) 4x - x = [12  9]
g) x^T =
[[4]
 [3]]
g) New dimension: 2 x 1
h) -
i) ||x|| = 5.0


In [48]:
# 10.1.2
v=np.array([[3],[7],[0],[11]])
print(f'a) Dimension: {v.shape[0]} x {v.shape[1]}')
print(f'b) 2v =\n{2*v}')
print(f"c) 5v + 2v =\n{add_mult_matrices(5*v,2*v,'add')}")
print(f"d) 4v - 2v =\n{add_mult_matrices(4*v,-2*v,'add')}")
print(f'e) v^T = {v.T.reshape(-1)} - Dimension: {v.T.shape[0]} x {v.T.shape[1]}')
print(f'f) ||v| = {np.sqrt(np.sum(v**2))}')

a) Dimension: 4 x 1
b) 2v =
[[ 6]
 [14]
 [ 0]
 [22]]
c) 5v + 2v =
[[21]
 [49]
 [ 0]
 [77]]
d) 4v - 2v =
[[ 6]
 [14]
 [ 0]
 [22]]
e) v^T = [ 3  7  0 11] - Dimension: 1 x 4
f) ||v| = 13.379088160259652


In [46]:
# 10.1.3
v1=np.array([4,3,1,5])
v2=np.array([2,3,1,1])

print(f'a) ||v1|| = {np.linalg.norm(v1)}')
print(f"a) ||v1|| = {np.sqrt(add_mult_matrices(v1.reshape(1,4),v1.reshape(4,1),'multiply').flat[0])}")
print(f'a) ||v1|| = {np.sqrt(np.sum(v1**2))}')
print()
print(f'b) ||v1 - v2|| = {np.linalg.norm(v1 - v2)}')
print(f"b) ||v1 - v2|| = {np.sqrt(add_mult_matrices((v1-v2).reshape(1,4),(v1-v2).reshape(4,1),'multiply').flat[0])}")
print(f'b) ||v1 - v2|| = {np.sqrt(np.sum((v1-v2)**2))}')

a) ||v1|| = 7.14142842854285
a) ||v1|| = 7.14142842854285
a) ||v1|| = 7.14142842854285

b) ||v1 - v2|| = 4.47213595499958
b) ||v1 - v2|| = 4.47213595499958
b) ||v1 - v2|| = 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [82]:
# 10.2.1
A=np.array([[2,1,-1],[1,-1,1]])
B=np.array([[4,-2,1],[2,-4,-2]])
C=np.array([[1,2],[2,1]])
D=np.array([[3,4],[4,3]])
E=np.array([[1],[2]])
I=np.array([[1,0],[0,1]])

print(f"a) 2A =\n{2 * A}")
print()
print(f"b) B - 2A =\n{add_mult_matrices(B, -2*A, "add")}")
print()
print(f"d) 2D - 3C =\n{add_mult_matrices(2*D, -3*C, "add")}")
print()
print(f"e) D^T + 2D =\n{add_mult_matrices(D.T, 2*D, "add")}")
print()
print(f"f) 2C^T - 2D^T =\n{add_mult_matrices(2*C.T,-2*D.T,"add")}")
print()
#print(f"g) A^T - B =\n{add_mult_matrices(A.T, -B, "add")}")
print(f"g) -")
print()
#print(f"h) AC = \n{add_mult_matrices(A,C,"multiply")}")
print(f"h) -")
print()
print(f"i) CD =\n{add_mult_matrices(C,D,"multiply")}")
print()
print(f"j) CB =\n{add_mult_matrices(C,B,"multiply")}")
print()
print(f"k) CI =\n{add_mult_matrices(C,I,"multiply")}")
print()
print(f"l) AB^T =\n{add_mult_matrices(A,B.T,"multiply")}")

a) 2A =
[[ 4  2 -2]
 [ 2 -2  2]]

b) B - 2A =
[[ 0 -4  3]
 [ 0 -2 -4]]

d) 2D - 3C =
[[3 2]
 [2 3]]

e) D^T + 2D =
[[ 9 12]
 [12  9]]

f) 2C^T - 2D^T =
[[-4 -4]
 [-4 -4]]

g) -

h) -

i) CD =
[[11 10]
 [10 11]]

j) CB =
[[  8 -10  -3]
 [ 10  -8   0]]

k) CI =
[[1 2]
 [2 1]]

l) AB^T =
[[5 2]
 [7 4]]


In [79]:
# 10.2.2
A = np.array([[2,3,4],[5,4,1]])
print(f"AA^T =\n{add_mult_matrices(A, A.T ,"multiply")}")

AA^T =
[[29 26]
 [26 42]]


In [78]:
# 10.2.3 
A, B, C = np.array([[1,2],[2,4]]), np.array([[2,1],[1,3]]), np.array([[4,3],[0,2]])
print(f"AB = AC - {bool(np.prod(add_mult_matrices(A, B ,"multiply").__eq__(add_mult_matrices(A, C, "multiply"))))}")
print(f"B = C - {bool(np.prod(B.__eq__(C)))}")

AB = AC - True
B = C - False


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [73]:
import numpy as np
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [74]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [75]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
